--- Dieses Modul behebt einige Fehler im Spiel.
--- 
--- #### Bug Fixes:
--- <li>Luxusgüter können in Dorflagern gelagert werden</li>
--- <li>Soldaten respawning für ME-Kaserne ist aktiv</li>
--- <li>Füge Burg und Lagerhaus als Lieferkontrollpunkte hinzu</li>
--- <li>IO-Interaktionsprüfungen für beide Güter, wenn sie verfügbar sind</li>
--- <li>Das Zerstören aller Einheiten zählt jetzt nicht mehr Standorte und spezielle Entitäten</li>
--- <li>Der große Dom zeigt den richtigen Namen in der Auswahl an</li>
--- <li>Das Hausmenü ist für Gebäude anderer Klimazonen angepasst</li>
--- <li>Fähigkeitshinweise werden nur ausgelöst, wenn der Spieler einen Ritter und ein Lagerhaus hat</li>
--- <li>Gelöschte Lagerfeuer von Banditen verusrachen keine Spielabstürze mehr</li>
---

